services:
  qdrant:
    container_name: qdrant-dev
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage:z

    restart: unless-stopped
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__STORAGE__PATH=/qdrant/storage
      - QDRANT__STORAGE__OPTIMIZE_ON_STARTUP=true
      - QDRANT__LOG_LEVEL=info
      - QDRANT__SERVICE__WORKERS=4
      - QDRANT__SERVICE__API_KEY=SUPER_SECRET_API_KEY 
      - QDRANT__SERVICE__ENABLE_TLS=false 
